const eventsData = {
    "2024-09-30": [
        {
            id: "monad-meet-1",
            title: "Meet Monad",
            time: "13:00-18:00",
            location: "72-13",
            travelTime: "21 min from hotel",
            preferred: true,
            hasMerch: true,
            hasFood: false,
            description: "MERCH available",
            nearestStation: "city-hall",
            stationName: "City Hall"
        },
        {
            id: "innoblock-2025",
            title: "Innoblock 2025",
            time: "09:30-18:30",
            location: "National Gallery Singapore",
            travelTime: "14 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "city-hall",
            stationName: "City Hall"
        },
        {
            id: "solana-apex",
            title: "Solana APEX - Singapore",
            time: "10:00-19:00",
            location: "Marina Bay Sands",
            travelTime: "17 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "bayfront",
            stationName: "Bayfront"
        },
        {
            id: "ai-frontier",
            title: "AI Frontier: Exploring the Next Era of AI",
            time: "14:00-19:00",
            location: "Gardens by the Bay (Flower Dome)",
            travelTime: "22 min from hotel",
            preferred: false,
            hasMerch: false,
            hasFood: false,
            description: "Flower dome experience",
            nearestStation: "bayfront",
            stationName: "Bayfront"
        },
        {
            id: "whitepaper-reading",
            title: "Whitepaper Reading",
            time: "13:30-15:00",
            location: "Museum of Ice",
            travelTime: "35 min from hotel",
            preferred: false,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "bugis",
            stationName: "Bugis",
            stationName: "Bugis"
        },
        {
            id: "bera-summit",
            title: "Bera Summit",
            time: "14:00-20:00",
            location: "Museum of Ice Singapore",
            travelTime: "35 min from hotel",
            preferred: true,
            hasMerch: true,
            hasFood: true,
            description: "MERCH + ICE CREAM",
            nearestStation: "bugis",
            stationName: "Bugis",
            stationName: "Bugis"
        },
        {
            id: "stablecoin-skai",
            title: "Stablecoin SKAI-Line by Algorand x Nansen",
            time: "17:00-21:00",
            location: "SKAI Restaurant",
            travelTime: "25 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: true,
            description: "",
            nearestStation: "bayfront",
            stationName: "Bayfront"
        },
        {
            id: "suifest-welcome",
            title: "SuiFest Welcome Reception",
            time: "18:00-22:00",
            location: "LAVO Italian restaurant (Marina Bay Sands)",
            travelTime: "17 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: true,
            description: "",
            nearestStation: "bayfront",
            stationName: "Bayfront"
        },
        {
            id: "block-par-tee",
            title: "Block Par-Tee with Cronos, AWS, ClickHouse & McKay",
            time: "18:00-21:00",
            location: "Par club Singapore",
            travelTime: "26 min from hotel",
            preferred: true,
            hasMerch: true,
            hasFood: true,
            description: "MERCH + dinner buffet",
            nearestStation: "orchard",
            stationName: "Orchard",
            stationName: "Orchard"
        },
        {
            id: "injective-apac",
            title: "Injective APAC Tour @Singapore",
            time: "18:00-22:00",
            location: "Hortus (Marina Bay Sands area)",
            travelTime: "27 min from hotel",
            preferred: true,
            hasMerch: true,
            hasFood: true,
            description: "MERCH + FOOD",
            nearestStation: "bayfront",
            stationName: "Bayfront"
        },
        {
            id: "immunefi-alpha",
            title: "Immunefi Alpha Night",
            time: "18:00-23:00",
            location: "Near hotel",
            travelTime: "12 min from hotel",
            preferred: true,
            hasMerch: true,
            hasFood: false,
            description: "MERCH available",
            nearestStation: "raffles-place",
            stationName: "Raffles Place",
            stationName: "Raffles Place"
        },
        {
            id: "cardano-happy-hour",
            title: "The Cardano Happy Hour",
            time: "19:00-23:00",
            location: "NCO Club",
            travelTime: "27 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: true,
            description: "Dinner",
            nearestStation: "marina-bay",
            stationName: "Marina Bay",
            stationName: "Marina Bay"
        },
        {
            id: "ath-ale-coinex",
            title: "ATH & Ale by CoinEx",
            time: "19:00-24:00",
            location: "LeVel33",
            travelTime: "12 min from hotel",
            preferred: false,
            hasMerch: true,
            hasFood: true,
            description: "MERCH + food",
            nearestStation: "raffles-place",
            stationName: "Raffles Place"
        },
        {
            id: "zircuit-proof-vibes",
            title: "Zircuit x Quantstamp x Caladan x Sharps Present Proof of Vibes",
            time: "21:00-03:00",
            location: "RASA space",
            travelTime: "16 min walk",
            preferred: false,
            hasMerch: true,
            hasFood: false,
            description: "MERCH available",
            nearestStation: "clarke-quay",
            stationName: "Clarke Quay"
        },
        {
            id: "crypto-noir",
            title: "Crypto Noir: After Party",
            time: "22:00-04:30",
            location: "Moon rooftop bar",
            travelTime: "10 min walking",
            preferred: false,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "raffles-place",
            stationName: "Raffles Place"
        },
        {
            id: "proof-ai-builder",
            title: "Proof of AI - Builder & Influencer Night",
            time: "19:00-23:00",
            location: "Blu Jaz, Clarke Quay",
            travelTime: "13 min from hotel",
            preferred: false,
            hasMerch: false,
            hasFood: true,
            description: "Dinner",
            nearestStation: "clarke-quay",
            stationName: "Clarke Quay"
        }
    ],

    "2024-10-01": [
        {
            id: "one-of-us",
            title: "One of Us",
            time: "07:30-08:30",
            location: "Bayfront Plaza Carpark",
            travelTime: "5 min from hotel",
            preferred: true,
            hasMerch: true,
            hasFood: false,
            description: "MERCH available",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        },
        {
            id: "suifest-run-club",
            title: "SuiFest Run Club 4k",
            time: "08:00-09:00",
            location: "The Lawn @ Marina Bay",
            travelTime: "5 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        },
        {
            id: "bitmart-cafe-day1",
            title: "Bitmart Cafe Day 1",
            time: "11:30-15:30",
            location: "PS Cafe Marina Bay Sands",
            travelTime: "5 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: true,
            description: "",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        },
        {
            id: "tokenization-connect",
            title: "Tokenization Connect w/ Midas, Euler, Apollo Crypto & PreStocks",
            time: "11:30-14:30",
            location: "Super Loco Customs House, 70 Collyer Quay",
            travelTime: "10 min from hotel",
            preferred: false,
            hasMerch: false,
            hasFood: true,
            description: "Food included",
            nearestStation: "raffles-place",
            stationName: "Raffles Place"
        },
        {
            id: "rwaifi-connect",
            title: "RWAiFi Connect • Bites & Insights – Redefining Finance in AI & Robotics",
            time: "12:00-16:00",
            location: "AWS Singapore Pte Office (SIN18)",
            travelTime: "15 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: true,
            description: "Lunch included",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        },
        {
            id: "base-builder-showcase",
            title: "Token 2049: Base Builder Showcase",
            time: "13:30-17:30",
            location: "OGBC Innovation Hub",
            travelTime: "20 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "bugis",
            stationName: "Bugis"
        },
        {
            id: "sandhouse-future",
            title: "SANDHOUSE: THE FUTURE, MADE COZY",
            time: "14:00-17:00",
            location: "GlassDome - Landmark of Good",
            travelTime: "15 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        },
        {
            id: "non-fungible-singapore",
            title: "Non-fungible Singapore",
            time: "17:00-22:00",
            location: "Spectrum by Phil Studio",
            travelTime: "20 min from hotel",
            preferred: false,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "clarke-quay",
            stationName: "Clarke Quay"
        },
        {
            id: "chainlink-evening",
            title: "Chainlink Evening Exchange",
            time: "18:00-21:00",
            location: "Wakuda",
            travelTime: "15 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: true,
            description: "",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        },
        {
            id: "kaito-homecoming",
            title: "Kaito Homecoming at TOKEN2049",
            time: "18:00-22:00",
            location: "The Executive Centre, Singapore Land Tower",
            travelTime: "10 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "raffles-place",
            stationName: "Raffles Place"
        },
        {
            id: "meme-recharge",
            title: "MEME Recharge Station",
            time: "18:00-23:00",
            location: "McDonald's Suntec City",
            travelTime: "15 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: true,
            description: "",
            nearestStation: "bugis",
            stationName: "Bugis"
        },
        {
            id: "edgex-connects",
            title: "edgeX CONNECTS ALL : The Trader's Edge",
            time: "18:00-23:00",
            location: "SKAI Bar",
            travelTime: "25 min from hotel",
            preferred: false,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        },
        {
            id: "dogelonmars",
            title: "Token2049 Dogelonmars",
            time: "18:00-20:00",
            location: "Brooklyn Bar",
            travelTime: "15 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "clarke-quay",
            stationName: "Clarke Quay"
        },
        {
            id: "builder-nights-metamask",
            title: "Builder Nights Singapore - Presented by MetaMask 🦊",
            time: "18:00-23:00",
            location: "Makansutra Gluttons Bay",
            travelTime: "10 min from hotel",
            preferred: false,
            hasMerch: false,
            hasFood: true,
            description: "",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        },
        {
            id: "token-love-music",
            title: "Token of Love Music Festival",
            time: "18:00-22:30",
            location: "The Meadow",
            travelTime: "30 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "sentosa",
            stationName: "Sentosa"
        },
        {
            id: "fameex-yacht",
            title: "FameEX Yacht Night — Maybe You're the One",
            time: "18:30-21:30",
            location: "One Marina Sentosa Cove Singapore",
            travelTime: "35 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "sentosa",
            stationName: "Sentosa"
        },
        {
            id: "agents-unleashed",
            title: "Agents Unleashed: The Next Wave",
            time: "18:30-21:30",
            location: "ArtScience Museum",
            travelTime: "15 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        },
        {
            id: "zoomex-tap-future",
            title: "Zoomex | Tap the Future",
            time: "19:00-23:00",
            location: "Avenue Lounge",
            travelTime: "20 min from hotel",
            preferred: true,
            hasMerch: true,
            hasFood: true,
            description: "Food + merch",
            nearestStation: "orchard",
            stationName: "Orchard"
        },
        {
            id: "cute-fest",
            title: "Cute Fest: Fugz, Plooshies, Ruyui",
            time: "19:00-22:00",
            location: "Lunì - Scent, Bar & Kitchen",
            travelTime: "25 min from hotel",
            preferred: false,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "clarke-quay",
            stationName: "Clarke Quay"
        },
        {
            id: "aptos-after-hours",
            title: "Aptos After Hours",
            time: "20:00-00:30",
            location: "RASA Space",
            travelTime: "16 min walk",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "clarke-quay",
            stationName: "Clarke Quay"
        },
        {
            id: "wizards-singapore",
            title: "Wizards in Singapore",
            time: "21:00-02:00",
            location: "Dashi Skypool",
            travelTime: "20 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        }
    ],

    "2024-10-02": [
        {
            id: "spicy-5k-chiliz",
            title: "Spicy 5k Run Chiliz",
            time: "07:30-08:30",
            location: "Marina Bay Sands",
            travelTime: "5 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        },
        {
            id: "unite-defi",
            title: "Unite DeFi",
            time: "10:00-17:00",
            location: "Art Science Museum",
            travelTime: "15 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        },
        {
            id: "suifest-day2",
            title: "SuiFest",
            time: "10:00-19:00",
            location: "Marina Bay Sands",
            travelTime: "5 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        },
        {
            id: "bitmart-cafe-day2",
            title: "Bitmart Cafe Day 2",
            time: "10:00-15:30",
            location: "PS Cafe Marina Bay Sands",
            travelTime: "5 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: true,
            description: "",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        },
        {
            id: "base-ignite-fire",
            title: "Base: Ignite Fire",
            time: "13:00-17:00",
            location: "So High",
            travelTime: "20 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "orchard",
            stationName: "Orchard"
        },
        {
            id: "kaia-dev",
            title: "KAIA Dev",
            time: "13:30-17:00",
            location: "Google Developers Space",
            travelTime: "15 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        },
        {
            id: "sanctuary",
            title: "The Sanctuary",
            time: "14:00-17:00",
            location: "Huone Singapore",
            travelTime: "15 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "marina-bay",
            stationName: "Marina Bay"
        },
        {
            id: "superconnect-sg",
            title: "Superconnect SG",
            time: "15:00-18:00",
            location: "Ngee Ann City",
            travelTime: "20 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "orchard",
            stationName: "Orchard"
        },
        {
            id: "oblique",
            title: "Oblique",
            time: "15:00-18:00",
            location: "MDLR",
            travelTime: "25 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "clarke-quay",
            stationName: "Clarke Quay"
        },
        {
            id: "arweave",
            title: "Arweave",
            time: "15:00-20:00",
            location: "Haus217",
            travelTime: "25 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "clarke-quay",
            stationName: "Clarke Quay"
        },
        {
            id: "founders-kol-party",
            title: "Founders and KOL Party",
            time: "17:00-20:00",
            location: "2 Keppel Bay Vista",
            travelTime: "40 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "sentosa",
            stationName: "Sentosa"
        },
        {
            id: "make-it-trade",
            title: "Make it Trade Cocktail",
            time: "18:00-22:00",
            location: "Red Dot Design Museum",
            travelTime: "15 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "chinatown",
            stationName: "Chinatown"
        },
        {
            id: "tron-afterparty",
            title: "TRON Afterparty",
            time: "18:30-23:30",
            location: "HaveFun Live Show (Bugis)",
            travelTime: "20 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "bugis",
            stationName: "Bugis"
        },
        {
            id: "qubic",
            title: "Qubic",
            time: "19:00-22:00",
            location: "Cargo 39",
            travelTime: "25 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "clarke-quay",
            stationName: "Clarke Quay"
        },
        {
            id: "midnight-plates",
            title: "Midnight Plates",
            time: "20:00-23:00",
            location: "Chinatown Complex",
            travelTime: "15 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: true,
            description: "",
            nearestStation: "chinatown",
            stationName: "Chinatown"
        },
        {
            id: "humanity-tashi",
            title: "Humanity & Tashi Official Lounge",
            time: "21:00-00:00",
            location: "Sentosa Cove",
            travelTime: "40 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "sentosa",
            stationName: "Sentosa"
        },
        {
            id: "blofin-berachain",
            title: "Blofin x Berachain",
            time: "21:00-00:00",
            location: "Marquee Singapore",
            travelTime: "35 min from hotel",
            preferred: true,
            hasMerch: false,
            hasFood: false,
            description: "",
            nearestStation: "sentosa",
            stationName: "Sentosa"
        }
    ]
};

// Station coordinates for mapping
const stationCoordinates = {
    "marina-bay": { x: 750, y: 450 },
    "raffles-place": { x: 700, y: 420 },
    "clarke-quay": { x: 680, y: 400 },
    "chinatown": { x: 650, y: 430 },
    "bugis": { x: 720, y: 380 },
    "orchard": { x: 600, y: 350 },
    "sentosa": { x: 650, y: 550 }
};

// Hotel location (assuming near Marina Bay)
const hotelLocation = { x: 730, y: 440 };